name: Exploring variables and secrets
on:
    push
env:
    CONTAINER_REGISTRY: docker.io
    DOCKER_USERNAME: dharmi1
    IMAGE_NAME: github-actions-ngnix

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Docker Build
              run: echo docker build -t ${{env.CONTAINER_REGISTRY}}/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

            - name: Docker Login
              env:
                DOCKER_PASSWORD: 23456dHaRmI
              run: echo docker login --username=${{ vars.DOCKER_USERNAME }}--password=$DOCKER_PASSWORD

            - name: Docker Publish
              run: echo docker push $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
            - name: Docker Run
              run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{vars.DOCKER_USERNAME}}/$IMAGE_NAME:latest